name: Update .gitignore

on: 
  workflow_call:
    inputs:
      url_suffix:
        description: 'Suffix for the Toptal URL'
        required: true
        type: string

jobs:
  update-gitignore:
    runs-on: ubuntu-latest
    env:
      ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      BRANCH: main
      COMMIT_MESSAGE: "Update .gitignore - Automated update [skip ci]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest .gitignore
        run: curl -s https://www.toptal.com/developers/gitignore/api/${{ inputs.url_suffix }} -o .gitignore

      - name: Check for changes
        id: git_diff
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .gitignore
          if git diff --cached --quiet; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV

      - name: Commit changes
        if: env.changes == 'true'
        run: git commit -m "${{ env.COMMIT_MESSAGE }}"

      - name: Fetch and rebase before push
        if: env.changes == 'true'
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}
          git fetch origin
          git rebase origin/${{ env.BRANCH }} --autostash

      - name: Push changes
        if: env.changes == 'true'
        run: git push origin HEAD:update-gitignore --force-with-lease

      - name: Create Pull Request
        if: env.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "${{ env.COMMIT_MESSAGE }}"
          branch: update-gitignore
          title: 'Update .gitignore'
          body: 'Automated update of .gitignore file'
          labels: update
